### ISSUE TITLE
Eraser Map 0.9.2 (play store beta) Crash on launch

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#593]
**Last reported** Today, 3:13 AM
**Reports this week** 2
**Reports total** 2
**Application version** 90299
**Android version** Android 6.0
**Device** Galaxy S6 Edge (zerolteatt)

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapzen.erasermap/com.mapzen.erasermap.controller.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mapzen.erasermap.model.ApiKeys.getRoutingKey()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
	at android.app.ActivityThread.access$1100(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mapzen.erasermap.model.ApiKeys.getRoutingKey()' on a null object reference
	at com.mapzen.erasermap.AndroidModule.provideRouteManager(AndroidModule.java:68)
	at com.mapzen.erasermap.AndroidModule_ProvideRouteManagerFactory.get(AndroidModule_ProvideRouteManagerFactory.java:23)
	at com.mapzen.erasermap.AndroidModule_ProvideRouteManagerFactory.get(AndroidModule_ProvideRouteManagerFactory.java:9)
	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
	at com.mapzen.erasermap.AndroidModule_ProvideMainPresenterFactory.get(AndroidModule_ProvideMainPresenterFactory.java:39)
	at com.mapzen.erasermap.AndroidModule_ProvideMainPresenterFactory.get(AndroidModule_ProvideMainPresenterFactory.java:13)
	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
	at com.mapzen.erasermap.controller.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:64)
	at com.mapzen.erasermap.controller.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:18)
	at com.mapzen.erasermap.DaggerEraserMapApplication_ApplicationComponent.inject(DaggerEraserMapApplication_ApplicationComponent.java:110)
	at com.mapzen.erasermap.controller.MainActivity.onCreate(MainActivity.kt:164)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
	... 9 more
```

**Comment by ecgreb** [comment]
@mjcunningham are you seeing this crash on cold start or after resuming from the background?

**Comment by ecgreb** [comment]
So far I am unable to reproduce on the Robin (6.0.1) or Note 3 (4.4.2). I tested both cold start and resume from background.

@sarahlensing can you try to reproduce this on your device? From looking at the code this stack trace seems very strange since the API keys should always be set by `InitActivity` before `MainActivity` is even started. Unless I am missing something?

**Comment by sarahlensing** [comment]
@ecgreb I'll take a look now and try to reproduce

**Comment by tallytalwar** [comment]
I just tried this on s6 edge, (6.0.1) running eraser-map 0.9.2. Can not reproduce this.

**Comment by sarahlensing** [comment]
@tallytalwar it usually manifests after the app has been in the background for a while and then you relaunch it. Try leaving EM in the background for a few hours and then relaunching it

Looking at logs for the activity lifecycle i see that the app goes through this flow when first launched:
```list
05-25 14:50:14.177  14659    14659           InitActivity  D  [onCreate]
05-25 14:50:14.347  14659    14659           InitActivity  D  [onStart]
05-25 14:50:14.347  14659    14659           InitActivity  D  [onResume]
05-25 14:50:15.587  14659    14659           InitActivity  D  [onPause]
05-25 14:50:15.687  14659    14659           MainActivity  D  [onCreate]
05-25 14:50:16.067  14659    14659           MainActivity  D  [onStart]
05-25 14:50:16.067  14659    14659           MainActivity  D  [onResume]
05-25 14:50:16.427  14659    14659           InitActivity  D  [onStop]
05-25 14:50:16.437  14659    14659           InitActivity  D  [onDestroy]
```

when put into the background:
```list
05-25 14:54:21.537  14659    14659           MainActivity  D  [onPause]
05-25 14:54:22.107  14659    14659           MainActivity  D  [onStop]
```

when relaunched from the background:
```list
05-25 14:54:53.647  14659    14659           MainActivity  D  [onStart]
05-25 14:54:53.647  14659    14659           MainActivity  D  [onResume]
```

Our `ApiKeys` object is a member of the application but it's configured in the `InitActivity`. What if we moved this into the `init` block of `ApiKeys`?

It is strange how the application could get into this state though since it should be holding on to the `ApiKeys` object unless its killed...this could be due to TouchWiz though

**Comment by ecgreb** [comment]
Very strange indeed. I like this idea but if we move reading/decoding the keys into the `ApiKeys` constructor then the question becomes where do we instantiate it. In `MainActivity`? In the application?

We will also need to verify that decoding the production keys is a repeatable operation.
