### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#663]
This is from the console.

Application version: 100099
Android 6.0
OnePlus One (A0001) 1

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapzen.erasermap/com.mapzen.erasermap.controller.MainActivity}: java.lang.IllegalStateException: crypt.decode(BuildConfig.VECTOR_TILE_API_KEY) must not be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: crypt.decode(BuildConfig.VECTOR_TILE_API_KEY) must not be null
	at com.mapzen.erasermap.model.ApiKeys.configureKeys(ApiKeys.kt:40)
	at com.mapzen.erasermap.model.ApiKeys.<init>(ApiKeys.kt:27)
	at com.mapzen.erasermap.model.ApiKeys.<init>(ApiKeys.kt:9)
	at com.mapzen.erasermap.model.ApiKeys$Companion.sharedInstance(ApiKeys.kt:20)
	at com.mapzen.erasermap.AndroidModule.provideApiKeys(AndroidModule.java:108)
	at com.mapzen.erasermap.AndroidModule_ProvideApiKeysFactory.get(AndroidModule_ProvideApiKeysFactory.java:18)
	at com.mapzen.erasermap.AndroidModule_ProvideApiKeysFactory.get(AndroidModule_ProvideApiKeysFactory.java:7)
	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
	at com.mapzen.erasermap.AndroidModule_ProvideRouteManagerFactory.get(AndroidModule_ProvideRouteManagerFactory.java:27)
	at com.mapzen.erasermap.AndroidModule_ProvideRouteManagerFactory.get(AndroidModule_ProvideRouteManagerFactory.java:10)
	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
	at com.mapzen.erasermap.AndroidModule_ProvideMainPresenterFactory.get(AndroidModule_ProvideMainPresenterFactory.java:47)
	at com.mapzen.erasermap.AndroidModule_ProvideMainPresenterFactory.get(AndroidModule_ProvideMainPresenterFactory.java:15)
	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
	at com.mapzen.erasermap.controller.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:68)
	at com.mapzen.erasermap.controller.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:19)
	at com.mapzen.erasermap.DaggerEraserMapApplication_ApplicationComponent.inject(DaggerEraserMapApplication_ApplicationComponent.java:123)
	at com.mapzen.erasermap.controller.MainActivity.onCreate(MainActivity.kt:154)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
	... 9 more

**Comment by ecgreb** [comment]
Very strange. If `BuildConfig.VECTOR_TILE_API_KEY` is indeed null this build should crash on all devices all the time.

All constant values in `BuildConfig` are generated at build time (hence the name) and should not change on a per launch basis.

**Comment by blair1618** [comment]
I read this crash to mean that the result of `crypt.decode()` was `null`, not the value of `BuildConfig.VECTOR_TILE_API_KEY` itself (which would indeed be very strange). That would then suggest a problem in the native decoding procedure, which is more likely to behave differently on different devices.

**Comment by tallytalwar** [comment]
I also get the same crash on my S5. This is the version from the play store.

```
D/AndroidRuntime(12214): Shutting down VM
E/AndroidRuntime(12214): FATAL EXCEPTION: main
E/AndroidRuntime(12214): Process: com.mapzen.erasermap, PID: 12214
E/AndroidRuntime(12214): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapzen.erasermap/com.mapzen.erasermap.controller.MainActivity}: java.lang.IllegalStateException: crypt.decode(BuildConfig.VECTOR_TILE_API_KEY) must not be null
E/AndroidRuntime(12214): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
E/AndroidRuntime(12214): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
E/AndroidRuntime(12214): 	at android.app.ActivityThread.access$900(ActivityThread.java:172)
E/AndroidRuntime(12214): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
E/AndroidRuntime(12214): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12214): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(12214): 	at android.app.ActivityThread.main(ActivityThread.java:5835)
E/AndroidRuntime(12214): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12214): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12214): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(12214): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/AndroidRuntime(12214): Caused by: java.lang.IllegalStateException: crypt.decode(BuildConfig.VECTOR_TILE_API_KEY) must not be null
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.model.ApiKeys.configureKeys(ApiKeys.kt:40)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.model.ApiKeys.<init>(ApiKeys.kt:27)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.model.ApiKeys.<init>(ApiKeys.kt:9)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.model.ApiKeys$Companion.sharedInstance(ApiKeys.kt:20)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.AndroidModule.provideApiKeys(AndroidModule.java:108)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.AndroidModule_ProvideApiKeysFactory.get(AndroidModule_ProvideApiKeysFactory.java:18)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.AndroidModule_ProvideApiKeysFactory.get(AndroidModule_ProvideApiKeysFactory.java:7)
E/AndroidRuntime(12214): 	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.AndroidModule_ProvideRouteManagerFactory.get(AndroidModule_ProvideRouteManagerFactory.java:27)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.AndroidModule_ProvideRouteManagerFactory.get(AndroidModule_ProvideRouteManagerFactory.java:10)
E/AndroidRuntime(12214): 	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.AndroidModule_ProvideMainPresenterFactory.get(AndroidModule_ProvideMainPresenterFactory.java:47)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.AndroidModule_ProvideMainPresenterFactory.get(AndroidModule_ProvideMainPresenterFactory.java:15)
E/AndroidRuntime(12214): 	at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.controller.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:68)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.controller.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:19)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.DaggerEraserMapApplication_ApplicationComponent.inject(DaggerEraserMapApplication_ApplicationComponent.java:123)
E/AndroidRuntime(12214): 	at com.mapzen.erasermap.controller.MainActivity.onCreate(MainActivity.kt:154)
E/AndroidRuntime(12214): 	at android.app.Activity.performCreate(Activity.java:6221)
E/AndroidRuntime(12214): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime(12214): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
E/AndroidRuntime(12214): 	... 10 more
W/ActivityManager(  889):   Force finishing activity com.mapzen.erasermap/.controller.MainActivity

```

**Comment by ecgreb** [comment]
Ah good catch. Yes that is probably the case.

**Comment by roman-yepishev** [comment]
I can confirm that the crash happens on Nexus 5 (Android 6.0.1) on 0.10.0:

```
07-12 08:24:25.419  2088  3213 I ActivityManager: Start proc 3221:com.mapzen.erasermap/u0a400 for activity com.mapzen.erasermap/.view.InitActivity
07-12 08:24:26.034  3221  3249 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-12 08:24:26.072  3221  3249 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
07-12 08:24:26.074  3221  3249 I OpenGLRenderer: Initialized EGL, version 1.4
07-12 08:24:26.174  2088  2134 I ActivityManager: Displayed com.mapzen.erasermap/.view.InitActivity: +771ms
07-12 08:24:27.224  2088  2914 I ActivityManager: START u0 {cmp=com.mapzen.erasermap/.controller.MainActivity} from uid 10400 on display 0
07-12 08:24:27.364  3221  3221 I System.out: SimpleCrypt decoding error: pad block corrupted
07-12 08:24:27.394  3221  3221 D AndroidRuntime: Shutting down VM
07-12 08:24:27.395  3221  3221 E AndroidRuntime: FATAL EXCEPTION: main
07-12 08:24:27.395  3221  3221 E AndroidRuntime: Process: com.mapzen.erasermap, PID: 3221
07-12 08:24:27.395  3221  3221 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapzen.erasermap/com.mapzen.erasermap.controller.MainActivity}: java.lang.IllegalStateException: crypt.decode(BuildConfig.VECTOR_TILE_API_KEY) must not be null

```

**Comment by ecgreb** [comment]
For those who have seen this bug how often does it occur? Are there any specific steps to reproduce (resume from background, rotate device, etc.)?

**Comment by roman-yepishev** [comment]
I have 100% success rate of reproducing the bug on launch, wasn't able to run 0.10.0 on my phone since upgrading from 0.9.2.
