### ISSUE TITLE
Crash when exiting route (or could be just before exiting)

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#740]
Splunk link: https://mint.splunk.com/dashboard/project/b4d64ff6/errors/7767008030

Log:

```
0java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapzen.android.lost.api.PendingResult com.mapzen.android.lost.internal.FusedLocationProviderService.requestLocationUpdates(com.mapzen.android.lost.api.LostApiClient, com.mapzen.android.lost.api.LocationRequest, com.mapzen.android.lost.api.LocationListener)' on a null object reference
1	at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:111)
2	at com.mapzen.erasermap.model.MapzenLocationImpl.startLocationUpdates(MapzenLocationImpl.kt:72)
3	at com.mapzen.erasermap.presenter.MainPresenterImpl.onClickStartNavigation(MainPresenterImpl.kt:375)
4	at com.mapzen.erasermap.controller.MainActivity$initReverseButton$3.onClick(MainActivity.kt:1003)
5	at android.view.View.performClick(View.java:5702)
6	at android.widget.TextView.performClick(TextView.java:10887)
7	at android.view.View$PerformClick.run(View.java:22541)
8	at android.os.Handler.handleCallback(Handler.java:739)
9	at android.os.Handler.dispatchMessage(Handler.java:95)
10	at android.os.Looper.loop(Looper.java:158)
11	at android.app.ActivityThread.main(ActivityThread.java:7229)
12	at java.lang.reflect.Method.invoke(Native Method)
13	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
14	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by tallytalwar** [comment]
Ok, I can reliably reproduce this now:

Steps:
1. Start navigation to any place.
2. Exit navigation, go back to default eraser-map view.
3. start another navigation (by hitting start navigation).
4. boom, crash!
