### ISSUE TITLE
EM crash fixes

### ISSUE THREAD

**Issue by sarahcodes100** [mapzen/eraser-map#834]
We've had a few crashes come in through Splunk:

**Comment by sarahcodes100** [comment]
```
java.lang.IllegalArgumentException: in == null
	at okio.Okio.source(Okio.java:127)
	at okio.Okio.source(Okio.java:220)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:193)
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:196)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:132)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:101)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by sarahcodes100** [comment]
```
java.lang.RuntimeException: Could not dispatch event: class com.mapzen.erasermap.model.event.LocationChangeEvent to handler [EventHandler public final void com.mapzen.erasermap.presenter.MainPresenterImpl.onLocationChangeEvent(com.mapzen.erasermap.model.event.LocationChangeEvent)]: null cannot be cast to non-null type android.widget.TextView
	at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
	at com.squareup.otto.Bus.dispatch(Bus.java:387)
	at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
	at com.squareup.otto.Bus.post(Bus.java:337)
	at com.mapzen.erasermap.model.MapzenLocationImpl.onLocationUpdate(MapzenLocationImpl.kt:86)
	at com.mapzen.erasermap.model.MapzenLocationImpl$locationListener$1.onLocationChanged(MapzenLocationImpl.kt:30)
	at com.mapzen.android.lost.internal.LostClientManager$1.notify(LostClientManager.java:156)
	at com.mapzen.android.lost.internal.LostClientManager$1.notify(LostClientManager.java:154)
	at com.mapzen.android.lost.internal.LostClientManager.iterateAndNotify(LostClientManager.java:303)
	at com.mapzen.android.lost.internal.LostClientManager.reportLocationChanged(LostClientManager.java:153)
	at com.mapzen.android.lost.internal.FusedLocationServiceCallbackManager.onLocationChanged(FusedLocationServiceCallbackManager.java:36)
	at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$1$1.run(FusedLocationProviderApiImpl.java:46)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.widget.TextView
	at com.mapzen.erasermap.view.InstructionAdapter.setPostText(InstructionAdapter.kt:84)
	at com.mapzen.erasermap.view.RouteModeView.playPostInstructionAlert(RouteModeView.kt:367)
	at com.mapzen.erasermap.presenter.RouteEngineListener.onInstructionComplete(RouteEngineListener.kt:43)
	at com.mapzen.helpers.RouteEngine.onLocationChanged(RouteEngine.java:86)
	at com.mapzen.erasermap.presenter.RoutePresenterImpl.onLocationChanged(RoutePresenterImpl.kt:31)
	at com.mapzen.erasermap.view.RouteModeView.onLocationChanged(RouteModeView.kt:228)
	at com.mapzen.erasermap.presenter.MainPresenterImpl.onLocationChangeEvent(MainPresenterImpl.kt:589)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
	at com.squareup.otto.Bus.dispatch(Bus.java:385)
```

**Comment by sarahcodes100** [comment]
```
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Double
	at com.mapzen.erasermap.model.MapzenLocationImpl.getBoundingBox(MapzenLocationImpl.kt:128)
	at com.mapzen.pelias.Pelias.search(Pelias.java:136)
	at com.mapzen.pelias.widget.PeliasSearchView.onQueryTextSubmit(PeliasSearchView.java:303)
	at android.support.v7.widget.SearchView.onSubmitQuery(SearchView.java:1242)
	at android.support.v7.widget.SearchView.setQuery(SearchView.java:616)
	at com.mapzen.erasermap.controller.MainActivity.initSearchView(MainActivity.kt:395)
	at com.mapzen.erasermap.controller.MainActivity.onCreateOptionsMenu(MainActivity.kt:378)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2856)
	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:362)
	at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
	at android.support.v7.app.AppCompatDelegateImplV9.preparePanel(AppCompatDelegateImplV9.java:1368)
	at android.support.v7.app.AppCompatDelegateImplV9.doInvalidatePanelMenu(AppCompatDelegateImplV9.java:1648)
	at android.support.v7.app.AppCompatDelegateImplV9$1.run(AppCompatDelegateImplV9.java:137)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```
